# Basics of NumPy Arrays

## NumPy array attributes

In [1]:
# determine size, shape, memory consumption and data types of arrays

In [2]:
import numpy as np
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size=6) # 1-D
x2 = np.random.randint(10, size=(3,4)) # 2-D
x3 = np.random.randint(10, size=(3,4,5)) # 3-D

- ndim = # of dimensions
- shape = size of each dimensions
- size = total size of array : # elements

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print("x3 dtype: ", x3.dtype)

x3 dtype:  int32


- itemsize: size in bytes of each element
- nbytes: total size in bytes of the array

In [5]:
print("x3 itemsize: ", x3.itemsize)
print("x3 nbytes: ", x3.nbytes)

x3 itemsize:  4
x3 nbytes:  240


## Array indexing
Get and set values of individual array elements

In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0] # first element

5

In [8]:
x1[4]

7

In [9]:
x1[-1] # last element

9

In [10]:
# comma separate for dimensional indexing
print(x2)
x2[2,2]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


7

In [11]:
x2[-1, -3] = 0
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 0 7 7]]


NP arrays are fixed type. So changing the value of an int array to a float value, will cause the value to be truncated.
No warnings will be given!

In [12]:
x1[0] = 3.1415926

In [13]:
x1

array([3, 0, 3, 3, 7, 9])

## Slicing, accessing subarrays
```python 
x[start:stop:step]
```
defaults: start = 0, stop = size of dimension, step = 1

In [14]:
x = np.arange(1,11) #up to but not including
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
print(x[:5]) # first 5 elements
print(x[5:]) # everything after index 5

[1 2 3 4 5]
[ 6  7  8  9 10]


In [16]:
x[2:4]

array([3, 4])

In [17]:
# when step is negative, start and stop are swapped
x[::-1] # entire thing reversed

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
x[0:4:-1]

array([], dtype=int32)

In [19]:
x[4:0:-1] #have to give start and stop in reverse order

array([5, 4, 3, 2])

## Multi-dimensional subarrays

In [20]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 0, 7, 7]])

In [21]:
x2[:2, :3] #2 rows, 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [22]:
x2[:, ::2] #all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [23]:
x2[::-1, ::-1] #reverse everything

array([[7, 7, 0, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [24]:
x2[:1, :] # first row

array([[3, 5, 2, 4]])

In [25]:
x2[0, :] # same as above, but simpler

array([3, 5, 2, 4])

In [26]:
x2[:, 0] # first column given as a row

array([3, 7, 1])

In [27]:
x2[0] # single value given to multi-dimension: defaults to row index with all columns

array([3, 5, 2, 4])

In [28]:
x2[1]

array([7, 6, 8, 8])

## subarrays are not copies

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 0, 7, 7]])

In [30]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [31]:
x2_sub[0,:] = 0
x2_sub

array([[0, 0],
       [7, 6]])

In [32]:
x2

array([[0, 0, 2, 4],
       [7, 6, 8, 8],
       [1, 0, 7, 7]])

useful to make changes to overall array when working with subarrays. But potentially dangerous if just playing around with subarrays

## make copies with .copy()

In [33]:
x2copy = x2[:2, :2].copy()
print(x2copy)

[[0 0]
 [7 6]]


In [34]:
x2copy[0,:] = [1, 2]
x2copy

array([[1, 2],
       [7, 6]])

In [35]:
x2

array([[0, 0, 2, 4],
       [7, 6, 8, 8],
       [1, 0, 7, 7]])

## reshape arrays with x.reshape((rows, columns))

In [36]:
grid = np.arange(1, 10).reshape((3, 3)) #must reshape to array with same # elements as initial
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### reshape with np.newaxis

In [37]:
newgrid = np.arange(1,10)
newgrid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
newgrid[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
newgrid[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## array concatenation and splitting

- np.concatenate: like it sounds, np.concatenate([array1, array2], axis=0,1,2,...)
<br>if your arrays have different dimensions:
- np.vstack: vertically stack em
- np.hstack: horizontally stack em
- np.dstack: stack along 3rd dimension

In [41]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [43]:
grid = np.array([[1, 2, 3],
               [4, 5, 6]])

In [44]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([grid, x])

ValueError: all the input arrays must have same number of dimensions

In [46]:
np.vstack([grid, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [48]:
np.vstack([grid, x, y])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
np.hstack([grid, y])

ValueError: all the input arrays must have same number of dimensions

In [51]:
np.concatenate([grid, grid], axis=1) # axis 0 indexed

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
np.dstack([grid, grid])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

## splitting arrays
-  np.split
 - np.hsplit
    -  np.vsplit
    
<br> just testing bullet points :)

In [54]:
# give indices of split points. 2 split points = 3 arrays
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7]


In [56]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
upper, lower = np.vsplit(grid, [3])
print(upper)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
print(lower)

[[12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [1])

In [66]:
print(left)

[[ 0]
 [ 4]
 [ 8]
 [12]]


In [67]:
print(right)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


np.dsplit to split on 3rd axis